name: AI-Discipline-Guard
on: [pull_request]

jobs:
  verify-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -q -U google-generativeai
      - name: Run AI Guard
        env:
          GEMINI_API_KEY: ${{ secrets.BRMS }}
        run: python ai_checker.py
